FROM node:22-slim

# Install required system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install


# Copy the rest of the application code
COPY . .

# Generate prisma client
RUN npm run prisma -- generate

# Start the Temporal worker
CMD [ "npm", "run", "pending-notifications-client" ]