FROM node:22-bullseye-slim

RUN apt-get update -y && \
    apt-get install -y openssl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate prisma client
RUN npm run prisma -- generate

# Expose port 3000
EXPOSE 3000

# Start the app
CMD [ "npm", "run", "dev" ]
